<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title><?php echo $currentPage; ?>Fashion Facts | Assignment 4: Information Architecture | Team Atlantis</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/navigation.css">
    <link rel="stylesheet" href="css/footer.css">
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">

</head>
<body class="container">
	<header>
		<h1><a href="index.php">Fashion Facts</a></h1>
	</header>

	<?php include "inc/nav.inc"; ?>

 
	<main>